### ISSUE TITLE
fringeSet.add callback is no function, says xs

### ISSUE THREAD

**Issue by dckc** [Agoric/make-hardener#47]
On moddable's xs, this `forEach` call fails with `@agoric/harden/dist/harden.esm.js (122) # Break: (host): callback is no function!`:

https://github.com/Agoric/make-hardener/blob/5ea2bc1779ec9f91284279f222533269285eeff7/src/index.js#L176

This seems to work:

```js
      toFreeze.forEach(it => fringeSet.add(it), fringeSet);
```

This is in make-hardener 0.0.4 from harden 0.0.4 from SwingSet v0.0.19-2-g0037223

**Comment by dckc** [comment]
oddly, printing the `typeof fringeSet.add` gives `function`. 

```js
      trace(`callback type? ${typeof fringeSet.add}\n`);
```

@phoddie got any more clues for me? (no rush)

**Comment by phoddie** [comment]
Unlikely to solve this from the code fragment. If you can reduce the problem to a small code snippet, that would be ideal. If not, would you provide the project (manifest and sources)?

**Comment by dckc** [comment]
The following main.js and manifest gives the same symptoms:

```js
export default function main() {
  const toFreeze = new Set([1, 2, 3]);
  const fringeSet = new WeakSet();

  trace(`typeof callback: ${typeof fringeSet.add}\n`);
  toFreeze.forEach(fringeSet.add, fringeSet);
}
```

```json
{
  "include": [ "$(MODDABLE)/examples/manifest_base.json" ],
  "modules": { "*": [ "./main" ] },
}
```

output:
```
typeof callback: function
/home/connolly/projects/moddable/examples/js/setAdd/main.js (6) # Break: (host): callback is no function!
```

**Comment by phoddie** [comment]
Thanks for preparing the fragment. That made it straightforward to track this down.

There was a bug in XS when `mxHostFunctionPrimitive` is used (it is always enabled in the Moddable SDK runtime) which caused a failure when using native host functions as callbacks with built-ins. That has been fixed.

For the example above to work, it is necessary to modify the call to `forEach` to include the optional `this` parameter.

```
toFreeze.forEach(fringeSet.add, fringeSet);
```

**Comment by dckc** [comment]
confirmed, this is fixed as of https://github.com/Moddable-OpenSource/moddable/commit/b1b6b5d06adb02ee80aa6ffa447a9b9907292354

looks like it was fixed in these two:

https://github.com/Moddable-OpenSource/moddable/commit/1a780c0d8972f5af2168d555c17a6f762e130818
https://github.com/Moddable-OpenSource/moddable/commit/cbe1892e237247d7272c6f1c354bc8b46d21c54f
